from tkinter import * 
aken = Tk() 
aken.title("okno")
aken.geometry("600x600")
f1=Frame(aken,width=200,height=300)
f1.pack(side=LEFT)
f2=Frame(aken,width=400,height=300)
f2.pack(side=LEFT)
pea=Canvas()
ca= Canvas(f2, width=400, height=300, bg="red")
CheckVar1=IntVar()
CheckVar2=IntVar()
CheckVar3=IntVar()
CheckVar4=IntVar()
CheckVar5=IntVar()
c1=Checkbutton(f1,text="pea",variable=CheckVar1,font="Calibri 26",command=...)
c2=Checkbutton(f1,text="nina",variable=CheckVar2,font="Calibri 26",command=...)
c3=Checkbutton(f1,text="suu",variable=CheckVar3,font="Calibri 26",command=...)
c4=Checkbutton(f1,text="silm1",variable=CheckVar4,font="Calibri 26",command=...)
c5=Checkbutton(f1,text="silm2",variable=CheckVar5,font="Calibri 26",command=...)
c1.pack()
c2.pack()
c3.pack()
c4.pack()
c5.pack()


aken.mainloop()